### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by varsha1288** [dgg32/kegg_disease#2]
Hello,

After step 4, can you please link - the instructions that need to be followed.

Thanks,
Varsha

**Comment by varsha1288** [comment]
Found it on medium. Thanks!!

**Comment by dgg32** [comment]
@varsha1288 Hi thank you for pointing out, I added the link in readme now. Thanks.

https://towardsdatascience.com/neo4j-for-diseases-959dffb5b479
